#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
/home/alex/.local/bin/wallpaper & 	# local wallpaper
#/home/alex/.local/bin/bing-wallpaper &  # download server 'Bing' pictures ( reload file 1m )
#mopidy &
setxkbmap -layout "us,ru" -option 'grp:ctrl_shift_toggle' &
notify-send -i /home/alex/.local/share:-/home/alex/.local/share/larbs/larbs.png "Welcome to LARBS" "Press super+F1 for the help menu." # LARBSWELCOME

xrandr --output LVDS-1 --primary --mode 1366x768 --pos 0x851 --rotate normal --output VGA-1 --mode 1024x768 --pos 0x0 --rotate normal --output HDMI-1 --off
