#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

xsetroot -cursor_name left_ptr

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
#mainmonitor="$(bspc query --monitors --names | grep LVDS | head -n 1)"
#second_monitor="$(bspc query --monitors --names | grep VGA | head -n 1)"
#
# if ! echo "$mainmonitor" | grep VGA >/dev/null 2>&1; then
# 	xrandr --output "$mainmonitor" --primary --mode 1366x768 --pos 0x851 --rotate normal --output \
#	                "$second_monitor" --mode 1024x768 --pos 0x0 --rotate normal
# else
# 	mainmonitor="LVDS-1 --primary --mode 1366x768 --pos 0x851 --rotate normal"
# 	xrandr --output "$mainmonitor"
# fi


# Start workspaces on the main monitor.
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor "$mainmonitor" -d I II III IV V
#bspc monitor "$second_monitor" -d VI VII VIII IX X
#bspc monitor LVDS-1 -d I II III IV V
#bspc monitor VGA-1 -d VI VII VIII IX X

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.

bspc config border_width 3
bspc config window_gap 12
bspc config top_padding 0	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle				false
# --- color
bspc config normal_border_color "#FF782e43"
bspc config focused_border_color "#00ff00"
bspc config presel_feedback_color "#746081"

##############################################################
# --- workground
bspc rule -a Zathura                      state=tiled
bspc rule -a ViberPC         desktop='^6' state=tiled    follow=on
bspc rule -a Gimp            desktop='^8' state=floating follow=on
bspc rule -a Inkscape        desktop='^8' state=floating follow=on
bspc rule -a brave           desktop='^2'
bspc rule -a mpv                          state=tiled
bspc rule -a wt              desktop='^1'                          focus=on
bspc rule -a Screenkey                                                        manage=off


##################
dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid -f "$TERMINAL" -n "$dropdownname" -e dropdown >/dev/null 2>&1
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

#bspc config external_rules_command "$(which floaters)"



##############################################################
# --- Startup apps
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launchpolybar.sh
