#!/bin/zsh -f


# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

xkbcomp /home/alex/.config/xkb/my $DISPLAY

setxkbmap -layout "us,ru" -option 'grp:ctrl_shift_toggle' &
xcape -e Super_L Escape
. "$HOME/.profile"
#ssh-agent dwm

#session=${1:-dwm}
#session=${1:-bspwm}
session=${1:-xmonad}

case $session in
    dwm) 	    exec ssh-agent dwm;;
    bspwm) 	    exec ssh-agent bspwm;;
    xmonad)
        xsetroot -cursor_name left_ptr
        exec ssh-agent xmonad;;
    # No known session, try to run it as command
    *                 ) exec $1;;
esac
